[package]
name = "regionx"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "regionx"
crate-type = ["cdylib"]

[dependencies]
astroxide = "0.0.6"
pyo3 = "0.27.0"
